apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
  labels:
    app: taskflow
data:
  APP_ENV: "development"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  PORT: "8080"
  NOTIFICATION_PORT: "8081"